import type { Metadata } from 'next';
import { Inter, Outfit } from 'next/font/google';
import './styles/globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import GlobalContextProvider from '../context/ContextApi';
import { ThemeProvider } from '@/providers/theme-providers';

const inter = Inter({ subsets: ['latin'] });

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <GlobalContextProvider>
          <body className={outfit.className}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </body>
        </GlobalContextProvider>
      </html>
    </ClerkProvider>
  );
}
